//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_6_Stepanyan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Order_Afrticle { get; set; }
        public string Date_Order { get; set; }
        public string Date_Of_delevery { get; set; }
        public int PickPoint { get; set; }
        public string Code { get; set; }
        public int Id_Status { get; set; }
    
        public virtual IdStatus IdStatus { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
