//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_6_Stepanyan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int IdProductName { get; set; }
        public int IdManufacture { get; set; }
        public int IdSupplier { get; set; }
        public int IdCategory { get; set; }
        public string Article { get; set; }
        public double Price { get; set; }
        public int DiscountMax { get; set; }
        public int DiscountNow { get; set; }
        public int ProductInStock { get; set; }
        public string ProductDescription { get; set; }
        public string Image { get; set; }
        public byte[] ProductImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
